import {
  GraduationCap,
  BookOpen,
  Zap,
  Calendar,
  Rocket,
  Atom,
  Wrench,
  Target,
  ShoppingCart,
  MapPin,
  Briefcase,
  Palette,
  Code,
  Github,
  Linkedin,
  Twitter,
  Mail,
  Phone,
  ExternalLink,
  FolderGit2,
  LayoutDashboard,
  User,
  Send,
  CheckCircle,
  Award,
  Users,
  Globe,
  Server,
  Database,
  Cloud,
  Sparkles,
  Layers,
  Cpu,
  Workflow,
  Box,
  Smartphone,
  Monitor,
  Activity,
  Lightbulb,
  TrendingUp,
  Link,
  AlertCircle,
  Star,
  Menu,
  Facebook,
  Instagram,
  X, // close icon
} from 'lucide-react';

export const ICON_MAP = {
  // ── Lowercase (existing) ────────────────────────────
  graduation: GraduationCap,
  book: BookOpen,
  zap: Zap,
  calendar: Calendar,
  menu: Menu,
  rocket: Rocket,
  atom: Atom,
  wrench: Wrench,
  target: Target,
  'trending-up': TrendingUp,
  cart: ShoppingCart,
  dashboard: LayoutDashboard,
  pin: MapPin,
  briefcase: Briefcase,
  phone: Phone,
  mail: Mail,
  palette: Palette,
  code: Code,
  server: Server,
  database: Database,
  cloud: Cloud,
  tool: Wrench,
  layers: Layers,
  cpu: Cpu,
  workflow: Workflow,
  box: Box,
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  external: ExternalLink,
  folder: FolderGit2,
  user: User,
  send: Send,
  check: CheckCircle,
  award: Award,
  users: Users,
  globe: Globe,
  sparkles: Sparkles,
  smartphone: Smartphone,
  monitor: Monitor,
  activity: Activity,
  lightbulb: Lightbulb,
  link: Link,
  'alert-circle': AlertCircle,
  star: Star,

  // ── CamelCase / missing aliases (so components work unchanged) ─
  GraduationCap,
  BookOpen,
  Zap,
  Calendar,
  Rocket,
  React: Atom, // maps to Atom (no official React icon)
  Server,
  Target,
  MapPin,
  Briefcase,
  Code,
  Palette,
  Globe,
  Lightbulb,
  x: X, // close icon – now available as <Icon name="x" />

  // Add any other exact names your components use here
};
